version: "3.8"

networks:
  selenium_net:
    external: true

services:
  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    networks:
      - selenium_net

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - bot_data:/_data
    working_dir: /_data
    command: ["python", "bot.py"]
    depends_on:
      - selenium
    networks:
      - selenium_net

volumes:
  bot_data:
